# Generated by Django 5.2.6 on 2025-11-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestioncars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('nombre', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='mot_de_pass',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='nom',
            new_name='username',
        ),
    ]
